DWAPlannerROS:

  max_vel_x: 4.0 
  min_vel_x: 0.0 

  max_trans_vel: 3 
  min_trans_vel: 0.1 
  trans_stopped_vel: 0.1

  max_rot_vel: 3.0 
  min_rot_vel: 0.4  
  rot_stopped_vel: 0.2
  
  acc_lim_x: 1.5
  acc_lim_theta: 2.5

  yaw_goal_tolerance: 1  #(double, default: 0.05)
  xy_goal_tolerance: 0.3  #(double, default: 0.10)

  sim_time: 2.0     
  vx_samples: 6       
  vy_samples: 0      
  vtheta_samples: 20 

  #The weighting for how much the controller should stay close to the path it was given
  path_distance_bias: 64.0  #(double, default: 32.0)权重越大小车走的路线越接近全局路径 

  #The weighting for how much the controller should attempt to reach its local goal, also controls speed   
  goal_distance_bias: 24.0   #(double, default: 24.0)   

  #The weighting for how much the controller should attempt to avoid obstacles
  occdist_scale: 0.5      #(double, default: 0.325)   
  forward_point_distance: 0.325 
  stop_time_buffer: 0.2        
  scaling_speed: 0.25          
  max_scaling_factor: 0.2      

  oscillation_reset_dist: 0.1  

  publish_traj_pc : true
  publish_cost_grid_pc: true
  global_frame_id: odom

  holonomic_robot: false
